/////////////////////////////////////////////////////////////////////////////////////////////
// GLVerProcAddr.cpp
//
// Getting OpenGL Version Procedure Address 
/////////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////////
void CGLDevInfo::GetVerProcAddr()
{
    // GL_VERSION_1_3
    int major = 4; 
    int minor = 4;
    //glGetIntegerv(GL_MAJOR_VERSION, &major);
    //glGetIntegerv(GL_MINOR_VERSION, &minor);

    // GL_VERSION_1_3
    bool bversion = ((major > 1) || (major == 1 && minor >= 3));
    if(!bversion)
        return ;

    OPENGL_GET_PROC(PFNGLACTIVETEXTUREPROC, glActiveTexture);
    OPENGL_GET_PROC(PFNGLSAMPLECOVERAGEPROC, glSampleCoverage);
    OPENGL_GET_PROC(PFNGLCOMPRESSEDTEXIMAGE3DPROC, glCompressedTexImage3D);
    OPENGL_GET_PROC(PFNGLCOMPRESSEDTEXIMAGE2DPROC, glCompressedTexImage2D);
    OPENGL_GET_PROC(PFNGLCOMPRESSEDTEXIMAGE1DPROC, glCompressedTexImage1D);
    OPENGL_GET_PROC(PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC, glCompressedTexSubImage3D);
    OPENGL_GET_PROC(PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC, glCompressedTexSubImage2D);
    OPENGL_GET_PROC(PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC, glCompressedTexSubImage1D);
    OPENGL_GET_PROC(PFNGLGETCOMPRESSEDTEXIMAGEPROC, glGetCompressedTexImage);

    OPENGL_GET_PROC(PFNGLCLIENTACTIVETEXTUREPROC, glClientActiveTexture);
    OPENGL_GET_PROC(PFNGLLOADTRANSPOSEMATRIXFPROC, glLoadTransposeMatrixf);
    OPENGL_GET_PROC(PFNGLLOADTRANSPOSEMATRIXDPROC, glLoadTransposeMatrixd);
    OPENGL_GET_PROC(PFNGLMULTTRANSPOSEMATRIXFPROC, glMultTransposeMatrixf);
    OPENGL_GET_PROC(PFNGLMULTTRANSPOSEMATRIXDPROC, glMultTransposeMatrixd);

    // GL_VERSION_1_2
    // GL_EXT_texture3D 
    OPENGL_GET_PROC(PFNGLTEXIMAGE3DEXTPROC, glTexImage3DEXT);
    OPENGL_GET_PROC(PFNGLTEXSUBIMAGE3DEXTPROC, glTexSubImage3DEXT);
    OPENGL_GET_PROC(PFNGLDRAWRANGEELEMENTSEXTPROC, glDrawRangeElementsEXT);

    // GL_EXT_blend_color
    OPENGL_GET_PROC(PFNGLBLENDCOLOREXTPROC, glBlendColorEXT);
    // GL_EXT_Blend_minmax
    OPENGL_GET_PROC(PFNGLBLENDEQUATIONEXTPROC, glBlendEquationEXT);


    // GL_VERSION_1_4
    bversion = ((major > 1) || (major == 1 && minor >= 4));
    if(!bversion)
        return ;

    // GL_VERSION_1_4
    OPENGL_GET_PROC(PFNGLBLENDFUNCSEPARATEPROC, glBlendFuncSeparate);
    OPENGL_GET_PROC(PFNGLMULTIDRAWARRAYSPROC, glMultiDrawArrays);
    OPENGL_GET_PROC(PFNGLMULTIDRAWELEMENTSPROC, glMultiDrawElements);
    OPENGL_GET_PROC(PFNGLPOINTPARAMETERFPROC, glPointParameterf);
    OPENGL_GET_PROC(PFNGLPOINTPARAMETERFVPROC, glPointParameterfv);
    OPENGL_GET_PROC(PFNGLPOINTPARAMETERIPROC, glPointParameteri);
    OPENGL_GET_PROC(PFNGLPOINTPARAMETERIVPROC, glPointParameteriv);
    OPENGL_GET_PROC(PFNGLFOGCOORDFPROC, glFogCoordf);
    OPENGL_GET_PROC(PFNGLFOGCOORDFVPROC, glFogCoordfv);
    OPENGL_GET_PROC(PFNGLFOGCOORDDPROC, glFogCoordd);
    OPENGL_GET_PROC(PFNGLFOGCOORDDVPROC, glFogCoorddv);
    OPENGL_GET_PROC(PFNGLFOGCOORDPOINTERPROC, glFogCoordPointer);

    OPENGL_GET_PROC(PFNGLSECONDARYCOLORPOINTERPROC, glSecondaryColorPointer);
    OPENGL_GET_PROC(PFNGLWINDOWPOS2DPROC, glWindowPos2d);
    OPENGL_GET_PROC(PFNGLWINDOWPOS2DVPROC, glWindowPos2dv);
    OPENGL_GET_PROC(PFNGLWINDOWPOS2FPROC, glWindowPos2f);
    OPENGL_GET_PROC(PFNGLWINDOWPOS2FVPROC, glWindowPos2fv);
    OPENGL_GET_PROC(PFNGLWINDOWPOS2IPROC, glWindowPos2i);
    OPENGL_GET_PROC(PFNGLWINDOWPOS2IVPROC, glWindowPos2iv);
    OPENGL_GET_PROC(PFNGLWINDOWPOS2SPROC, glWindowPos2s);
    OPENGL_GET_PROC(PFNGLWINDOWPOS2SVPROC, glWindowPos2sv);
    OPENGL_GET_PROC(PFNGLWINDOWPOS3DPROC, glWindowPos3d);
    OPENGL_GET_PROC(PFNGLWINDOWPOS3DVPROC, glWindowPos3dv);
    OPENGL_GET_PROC(PFNGLWINDOWPOS3FPROC, glWindowPos3f);
    OPENGL_GET_PROC(PFNGLWINDOWPOS3FVPROC, glWindowPos3fv);
    OPENGL_GET_PROC(PFNGLWINDOWPOS3IPROC, glWindowPos3i);
    OPENGL_GET_PROC(PFNGLWINDOWPOS3IVPROC, glWindowPos3iv);
    OPENGL_GET_PROC(PFNGLWINDOWPOS3SPROC, glWindowPos3s);
    OPENGL_GET_PROC(PFNGLWINDOWPOS3SVPROC, glWindowPos3sv); 

    // GL_VERSION_1_5
    bversion = ((major > 1) || (major > 1 && minor >= 5));
    if(!bversion)
        return ;

    // GL_VERSION_1_5
    OPENGL_GET_PROC(PFNGLGENQUERIESPROC, glGenQueries); 
    OPENGL_GET_PROC(PFNGLDELETEQUERIESPROC, glDeleteQueries); 
    OPENGL_GET_PROC(PFNGLISQUERYPROC, glIsQuery); 
    OPENGL_GET_PROC(PFNGLBEGINQUERYPROC, glBeginQuery); 
    OPENGL_GET_PROC(PFNGLENDQUERYPROC, glEndQuery); 
    OPENGL_GET_PROC(PFNGLGETQUERYIVPROC, glGetQueryiv); 
    OPENGL_GET_PROC(PFNGLGETQUERYOBJECTIVPROC, glGetQueryObjectiv); 
    OPENGL_GET_PROC(PFNGLGETQUERYOBJECTUIVPROC, glGetQueryObjectuiv); 
    OPENGL_GET_PROC(PFNGLBINDBUFFERPROC, glBindBuffer); 
    OPENGL_GET_PROC(PFNGLDELETEBUFFERSPROC, glDeleteBuffers); 
    OPENGL_GET_PROC(PFNGLGENBUFFERSPROC, glGenBuffers); 
    OPENGL_GET_PROC(PFNGLISBUFFERPROC, glIsBuffer); 
    OPENGL_GET_PROC(PFNGLBUFFERDATAPROC, glBufferData); 
    OPENGL_GET_PROC(PFNGLBUFFERSUBDATAPROC, glBufferSubData); 
    OPENGL_GET_PROC(PFNGLGETBUFFERSUBDATAPROC, glGetBufferSubData); 
    OPENGL_GET_PROC(PFNGLMAPBUFFERPROC, glMapBuffer);
    OPENGL_GET_PROC(PFNGLUNMAPBUFFERPROC, glUnmapBuffer); 
    OPENGL_GET_PROC(PFNGLGETBUFFERPARAMETERIVPROC, glGetBufferParameteriv); 
    OPENGL_GET_PROC(PFNGLGETBUFFERPOINTERVPROC, glGetBufferPointerv); 


    // GL_VERSION_2_0
    OPENGL_GET_PROC(PFNGLBLENDEQUATIONSEPARATEPROC, glBlendEquationSeparate);
    OPENGL_GET_PROC(PFNGLDRAWBUFFERSPROC, glDrawBuffers);
    OPENGL_GET_PROC(PFNGLSTENCILOPSEPARATEPROC, glStencilOpSeparate);
    OPENGL_GET_PROC(PFNGLSTENCILFUNCSEPARATEPROC, glStencilFuncSeparate);
    OPENGL_GET_PROC(PFNGLSTENCILMASKSEPARATEPROC, glStencilMaskSeparate);
    OPENGL_GET_PROC(PFNGLATTACHSHADERPROC, glAttachShader);
    OPENGL_GET_PROC(PFNGLBINDATTRIBLOCATIONPROC, glBindAttribLocation);
    OPENGL_GET_PROC(PFNGLCOMPILESHADERPROC, glCompileShader);
    OPENGL_GET_PROC(PFNGLCREATEPROGRAMPROC, glCreateProgram);
    OPENGL_GET_PROC(PFNGLCREATESHADERPROC, glCreateShader);
    OPENGL_GET_PROC(PFNGLDELETEPROGRAMPROC, glDeleteProgram);
    OPENGL_GET_PROC(PFNGLDELETESHADERPROC, glDeleteShader);
    OPENGL_GET_PROC(PFNGLDETACHSHADERPROC, glDetachShader);
    OPENGL_GET_PROC(PFNGLDISABLEVERTEXATTRIBARRAYPROC, glDisableVertexAttribArray);
    OPENGL_GET_PROC(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray);
    OPENGL_GET_PROC(PFNGLGETACTIVEATTRIBPROC, glGetActiveAttrib);
    OPENGL_GET_PROC(PFNGLGETACTIVEUNIFORMPROC, glGetActiveUniform);
    OPENGL_GET_PROC(PFNGLGETATTACHEDSHADERSPROC, glGetAttachedShaders);
    OPENGL_GET_PROC(PFNGLGETATTRIBLOCATIONPROC, glGetAttribLocation);
    OPENGL_GET_PROC(PFNGLGETPROGRAMIVPROC, glGetProgramiv);
    OPENGL_GET_PROC(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog);
    OPENGL_GET_PROC(PFNGLGETSHADERIVPROC, glGetShaderiv);
    OPENGL_GET_PROC(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog);
    OPENGL_GET_PROC(PFNGLGETSHADERSOURCEPROC, glGetShaderSource);
    OPENGL_GET_PROC(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation);
    OPENGL_GET_PROC(PFNGLGETUNIFORMFVPROC, glGetUniformfv);
    OPENGL_GET_PROC(PFNGLGETUNIFORMIVPROC, glGetUniformiv);
    OPENGL_GET_PROC(PFNGLGETVERTEXATTRIBDVPROC, glGetVertexAttribdv);
    OPENGL_GET_PROC(PFNGLGETVERTEXATTRIBFVPROC, glGetVertexAttribfv);
    OPENGL_GET_PROC(PFNGLGETVERTEXATTRIBIVPROC, glGetVertexAttribiv);
    OPENGL_GET_PROC(PFNGLGETVERTEXATTRIBPOINTERVPROC, glGetVertexAttribPointerv);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer);

    OPENGL_GET_PROC(PFNGLISPROGRAMPROC, glIsProgram);
    OPENGL_GET_PROC(PFNGLISSHADERPROC, glIsShader);
    OPENGL_GET_PROC(PFNGLLINKPROGRAMPROC, glLinkProgram);
    OPENGL_GET_PROC(PFNGLSHADERSOURCEPROC, glShaderSource);
    OPENGL_GET_PROC(PFNGLUSEPROGRAMPROC, glUseProgram);
    OPENGL_GET_PROC(PFNGLUNIFORM1FPROC, glUniform1f);
    OPENGL_GET_PROC(PFNGLUNIFORM2FPROC, glUniform2f);
    OPENGL_GET_PROC(PFNGLUNIFORM3FPROC, glUniform3f);
    OPENGL_GET_PROC(PFNGLUNIFORM4FPROC, glUniform4f);
    OPENGL_GET_PROC(PFNGLUNIFORM1IPROC, glUniform1i);
    OPENGL_GET_PROC(PFNGLUNIFORM2IPROC, glUniform2i);
    OPENGL_GET_PROC(PFNGLUNIFORM3IPROC, glUniform3i);
    OPENGL_GET_PROC(PFNGLUNIFORM4IPROC, glUniform4i);
    OPENGL_GET_PROC(PFNGLUNIFORM1FVPROC, glUniform1fv);
    OPENGL_GET_PROC(PFNGLUNIFORM2FVPROC, glUniform2fv);
    OPENGL_GET_PROC(PFNGLUNIFORM3FVPROC, glUniform3fv);
    OPENGL_GET_PROC(PFNGLUNIFORM4FVPROC, glUniform4fv);
    OPENGL_GET_PROC(PFNGLUNIFORM1IVPROC, glUniform1iv);
    OPENGL_GET_PROC(PFNGLUNIFORM2IVPROC, glUniform2iv);
    OPENGL_GET_PROC(PFNGLUNIFORM3IVPROC, glUniform3iv);
    OPENGL_GET_PROC(PFNGLUNIFORM4IVPROC, glUniform4iv);
    OPENGL_GET_PROC(PFNGLUNIFORMMATRIX2FVPROC, glUniformMatrix2fv);
    OPENGL_GET_PROC(PFNGLUNIFORMMATRIX3FVPROC, glUniformMatrix3fv);
    OPENGL_GET_PROC(PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv);
    OPENGL_GET_PROC(PFNGLVALIDATEPROGRAMPROC, glValidateProgram);

    // GL_VERSION_2_1
    bversion = ((major > 2) || (major == 2 && minor >= 1));
    if(!bversion)
        return ;

    // GL_VERSION_2_1
    OPENGL_GET_PROC(PFNGLUNIFORMMATRIX2X3FVPROC, glUniformMatrix2x3fv);
    OPENGL_GET_PROC(PFNGLUNIFORMMATRIX3X2FVPROC, glUniformMatrix3x2fv);
    OPENGL_GET_PROC(PFNGLUNIFORMMATRIX2X4FVPROC, glUniformMatrix2x4fv);
    OPENGL_GET_PROC(PFNGLUNIFORMMATRIX4X2FVPROC, glUniformMatrix4x2fv);
    OPENGL_GET_PROC(PFNGLUNIFORMMATRIX3X4FVPROC, glUniformMatrix3x4fv);
    OPENGL_GET_PROC(PFNGLUNIFORMMATRIX4X3FVPROC, glUniformMatrix4x3fv);

    // GL_VERSION_3_0
    bversion = (major >= 3);
    if(!bversion)
        return ;

    // GL_VERSION_3_0
    OPENGL_GET_PROC(PFNGLCOLORMASKIPROC, glColorMaski);
    OPENGL_GET_PROC(PFNGLGETBOOLEANI_VPROC, glGetBooleani_v);
    OPENGL_GET_PROC(PFNGLGETINTEGERI_VPROC, glGetIntegeri_v);
    OPENGL_GET_PROC(PFNGLENABLEIPROC, glEnablei);
    OPENGL_GET_PROC(PFNGLDISABLEIPROC, glDisablei);
    OPENGL_GET_PROC(PFNGLISENABLEDIPROC, glIsEnabledi);
    OPENGL_GET_PROC(PFNGLBEGINTRANSFORMFEEDBACKPROC, glBeginTransformFeedback);
    OPENGL_GET_PROC(PFNGLENDTRANSFORMFEEDBACKPROC, glEndTransformFeedback);
    OPENGL_GET_PROC(PFNGLBINDBUFFERRANGEPROC, glBindBufferRange);
    OPENGL_GET_PROC(PFNGLBINDBUFFERBASEPROC, glBindBufferBase);
    OPENGL_GET_PROC(PFNGLTRANSFORMFEEDBACKVARYINGSPROC, glTransformFeedbackVaryings);
    OPENGL_GET_PROC(PFNGLGETTRANSFORMFEEDBACKVARYINGPROC, glGetTransformFeedbackVarying);
    OPENGL_GET_PROC(PFNGLCLAMPCOLORPROC, glClampColor);
    OPENGL_GET_PROC(PFNGLBEGINCONDITIONALRENDERPROC, glBeginConditionalRender);
    OPENGL_GET_PROC(PFNGLENDCONDITIONALRENDERPROC, glEndConditionalRender);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBIPOINTERPROC, glVertexAttribIPointer);
    OPENGL_GET_PROC(PFNGLGETVERTEXATTRIBIIVPROC, glGetVertexAttribIiv);
    OPENGL_GET_PROC(PFNGLGETVERTEXATTRIBIUIVPROC, glGetVertexAttribIuiv);

    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI1IPROC, glVertexAttribI1i);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI2IPROC, glVertexAttribI2i);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI3IPROC, glVertexAttribI3i);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI4IPROC, glVertexAttribI4i);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI1UIPROC, glVertexAttribI1ui);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI2UIPROC, glVertexAttribI2ui);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI3UIPROC, glVertexAttribI3ui);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI4UIPROC, glVertexAttribI4ui);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI1IVPROC, glVertexAttribI1iv);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI2IVPROC, glVertexAttribI2iv);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI3IVPROC, glVertexAttribI3iv);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI4IVPROC, glVertexAttribI4iv);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI1UIVPROC, glVertexAttribI1uiv);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI2UIVPROC, glVertexAttribI2uiv);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI3UIVPROC, glVertexAttribI3uiv);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI4UIVPROC, glVertexAttribI4uiv);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI4BVPROC, glVertexAttribI4bv);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI4SVPROC, glVertexAttribI4sv);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI4UBVPROC, glVertexAttribI4ubv);
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBI4USVPROC, glVertexAttribI4usv);
    OPENGL_GET_PROC(PFNGLGETUNIFORMUIVPROC, glGetUniformuiv);
    OPENGL_GET_PROC(PFNGLBINDFRAGDATALOCATIONPROC, glBindFragDataLocation);
    OPENGL_GET_PROC(PFNGLGETFRAGDATALOCATIONPROC, glGetFragDataLocation);

    OPENGL_GET_PROC(PFNGLUNIFORM1UIPROC, glUniform1ui);
    OPENGL_GET_PROC(PFNGLUNIFORM2UIPROC, glUniform2ui);
    OPENGL_GET_PROC(PFNGLUNIFORM3UIPROC, glUniform3ui);
    OPENGL_GET_PROC(PFNGLUNIFORM4UIPROC, glUniform4ui);
    OPENGL_GET_PROC(PFNGLUNIFORM1UIVPROC, glUniform1uiv);
    OPENGL_GET_PROC(PFNGLUNIFORM2UIVPROC, glUniform2uiv);
    OPENGL_GET_PROC(PFNGLUNIFORM3UIVPROC, glUniform3uiv);
    OPENGL_GET_PROC(PFNGLUNIFORM4UIVPROC, glUniform4uiv);
    OPENGL_GET_PROC(PFNGLTEXPARAMETERIIVPROC, glTexParameterIiv);
    OPENGL_GET_PROC(PFNGLTEXPARAMETERIUIVPROC, glTexParameterIuiv);
    OPENGL_GET_PROC(PFNGLGETTEXPARAMETERIIVPROC, glGetTexParameterIiv);
    OPENGL_GET_PROC(PFNGLGETTEXPARAMETERIUIVPROC, glGetTexParameterIuiv);
    OPENGL_GET_PROC(PFNGLCLEARBUFFERIVPROC, glClearBufferiv);
    OPENGL_GET_PROC(PFNGLCLEARBUFFERUIVPROC, glClearBufferuiv);
    OPENGL_GET_PROC(PFNGLCLEARBUFFERFVPROC, glClearBufferfv);
    OPENGL_GET_PROC(PFNGLCLEARBUFFERFIPROC, glClearBufferfi);
    OPENGL_GET_PROC(PFNGLGETSTRINGIPROC, glGetStringi);


    // GL_VERSION_3_1
    bversion = ((major > 3) || (major == 3 && minor >= 1));
    if(!bversion)
        return ;

    // GL_VERSION_3_1
    OPENGL_GET_PROC(PFNGLDRAWARRAYSINSTANCEDPROC, glDrawArraysInstanced);
    OPENGL_GET_PROC(PFNGLDRAWELEMENTSINSTANCEDPROC, glDrawElementsInstanced);
    OPENGL_GET_PROC(PFNGLTEXBUFFERPROC, glTexBuffer);
    OPENGL_GET_PROC(PFNGLPRIMITIVERESTARTINDEXPROC, glPrimitiveRestartIndex);


    // GL_VERSION_3_2
    bversion = ((major > 3) || (major == 3 && minor>=2));
    if(!bversion)
        return ;

    // GL_VERSION_3_2
    OPENGL_GET_PROC(PFNGLGETINTEGER64I_VPROC, glGetInteger64i_v);
    OPENGL_GET_PROC(PFNGLGETBUFFERPARAMETERI64VPROC, glGetBufferParameteri64v);
    OPENGL_GET_PROC(PFNGLFRAMEBUFFERTEXTUREPROC, glFramebufferTexture);


    // GL_VERSION_3_3
    bversion = ((major > 3) || (major==3 && minor>=3));
    if(!bversion)
        return ;

    // GL_VERSION_3_3
    OPENGL_GET_PROC(PFNGLVERTEXATTRIBDIVISORPROC, glVertexAttribDivisor);

    // GL_VERSION_4_0
    bversion = (major >= 4);
    if(!bversion)
        return ;

    // GL_VERSION_4_0
    OPENGL_GET_PROC(PFNGLMINSAMPLESHADINGPROC, glMinSampleShading);
    OPENGL_GET_PROC(PFNGLBLENDEQUATIONIPROC, glBlendEquationi);
    OPENGL_GET_PROC(PFNGLBLENDEQUATIONSEPARATEIPROC, glBlendEquationSeparatei);
    OPENGL_GET_PROC(PFNGLBLENDFUNCIPROC, glBlendFunci);
    OPENGL_GET_PROC(PFNGLBLENDFUNCSEPARATEIPROC, glBlendFuncSeparatei);

}
/////////////////////////////////////////////////////////////////////////////////////////////